import Foundation

enum TokenStepLocalization {
    private(set) static var selectedLanguage: TokenStepLanguage = .system

    static var language: TokenStepLanguage {
        selectedLanguage.resolved
    }

    static var locale: Locale {
        Locale(identifier: language.localeIdentifier)
    }

    static func apply(_ language: TokenStepLanguage) {
        selectedLanguage = language
    }

    static func text(_ key: String) -> String {
        guard language != .zhHans else { return key }
        return translations[language]?[key] ?? key
    }

    static func format(_ key: String, _ arguments: CVarArg...) -> String {
        format(key, arguments)
    }

    static func format(_ key: String, _ arguments: [CVarArg]) -> String {
        String(format: text(key), locale: locale, arguments: arguments)
    }

    private static let translations: [TokenStepLanguage: [String: String]] = [
        .en: [
            "自动": "Auto",
            "刘海左侧": "Left of notch",
            "刘海右侧": "Right of notch",
            "菜单栏": "Menu bar",
            "左侧": "Left",
            "右侧": "Right",
            "跟随系统": "Follow System",
            "自动匹配 macOS": "Match macOS",
            "准备更新": "Preparing update",
            "正在下载": "Downloading",
            "正在安装并重启": "Installing and relaunching",
            "更新失败": "Update failed",
            "菜单栏模式": "Menu bar mode",
            "自动：刘海旁": "Auto: beside notch",
            "自动：菜单栏": "Auto: menu bar",
            "鼠标移入后展开浮层": "Hover to expand",
            "鼠标移入后展开 Island": "Hover to expand Island",
            "仅使用右上角菜单栏入口": "Use menu bar only",
            "刷新": "Refresh",
            "打开 TokenStep": "Open TokenStep",
            "设置": "Settings",
            "等待同步": "Waiting to sync",
            "Token 采集超时，请稍后重试": "Token collection timed out. Please try again later.",
            "Token 重新校准未完成，已保留原统计。": "Token recalibration did not complete. The previous totals were preserved.",
            "TokenStep 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenStep recalibrated historical Token usage using true increments. The number may be lower, but no history was lost.",
            "关闭": "Close",
            "手动": "Manual",
            "%d 分钟": "%d min",
            "1 分钟": "1 min",
            "第 %d 圈": "Lap %d",
            "第 %d 圈 · %@": "Lap %d · %@",
            "已完成 %d 圈": "%d laps completed",
            "已完成 %@": "%@ completed",
            "每圈目标 %@": "%@ per lap",
            "少": "Less",
            "多": "More",
            "活跃": "Active",
            "达标": "Goal",
            "最高": "Best",
            "近 8 个月活动墙": "Last 8 Months",
            "颜色越深，越接近或超过每日目标": "Darker means closer to, or beyond, the daily goal",
            "颜色越深，用量越高；描边是今天": "Darker means more usage; outline marks today",
            "%d 个活跃日": "%d active days",
            "全部明细": "All Details",
            "%d 条记录，向下滚动查看完整历史": "%d records. Scroll down for full history",
            "最近 %d 天，适合保存为截图": "Last %d days, ready for screenshots",
            "日期": "Date",
            "Token 消耗": "Token Usage",
            "消耗金额": "Cost",
            "主力工具": "Main Tool",
            "无": "None",
            "累计 Token 消耗": "Total Token Usage",
            "等待下一次同步": "Waiting for next sync",
            "最近 30 天": "Last 30 Days",
            "颜色越深，圈数越高": "Darker means a higher lap",
            "柱越高，用量越多；颜色代表客户端": "Taller bars mean more usage; colors show clients",
            "柱越高，用量越多": "Taller bars mean more usage",
            "颜色代表客户端": "Colors show clients",
            "今天 %@": "Today %@",
            "/ %@ 每圈": "/ %@ per lap",
            "圈数进度": "Lap Progress",
            "按客户端": "By Client",
            "按模型": "By Model",
            "今日客户端": "Today by Client",
            "今日模型": "Today by Model",
            "累计总量分布": "Total distribution",
            "主力模型": "Top Models",
            "本月均值": "Monthly Avg",
            "活跃天数": "Active Days",
            "达标天数": "Goal Days",
            "有 AI 使用的日期": "Days with AI usage",
            "达到每日目标": "Reached daily goal",
            "%d圈完成": "Lap %d done",
            "%@进行中": "%@ in progress",
            "所有本机记录": "All local records",
            "今日": "Today",
            "历史": "History",
            "统计": "Analytics",
            "模型与工具": "Models & Tools",
            "隐私": "Privacy",
            "今日消耗": "Today",
            "历史活动": "History",
            "用量统计": "Analytics",
            "今天的 Token 使用节奏": "Today’s token rhythm",
            "长期节奏和所有历史记录": "Long-term rhythm and all history",
            "按客户端和模型拆开看": "Break down by client and model",
            "只统计数量，不读取内容": "Only counts usage, never reads content",
            "保存当前页 PNG（最近 30 天）": "Save Page PNG (Last 30 Days)",
            "保存当前页 PNG": "Save Page PNG",
            "复制当前页截图": "Copy Page Screenshot",
            "截取当前页": "Capture Page",
            "更新": "Updated",
            "同步中": "Syncing",
            "已同步": "Synced",
            "暂无数据": "No data yet",
            "数据待更新": "Needs refresh",
            "同步失败": "Sync failed",
            "部分来源失败": "Some sources failed",
            "显示最后成功数据": "Showing last successful data",
            "最后成功 %@": "Last success %@",
            "%d 天前": "%d d ago",
            "消耗金额（估算）": "Cost (est.)",
            "按 API 列表价估算，不代表订阅或实际账单。": "Estimated from API list prices; not your subscription or actual bill.",
            "失败来源：%@": "Failed sources: %@",
            "数据状态说明": "Data status legend",
            "数据在正常刷新周期内成功获取。": "Data was captured successfully within the normal refresh cycle.",
            "超过正常刷新周期，最近一次尝试没有失败。": "Past the normal refresh cycle; the latest attempt did not fail.",
            "最近一次尝试失败，当前展示最后成功数据。": "The latest attempt failed; the last successful data is shown.",
            "同一轮刷新中部分数据来源失败，其余正常。": "Some sources failed in the latest refresh; the rest are fine.",
            "该数据从未成功获取，不会显示为 0。": "This data has never been captured; it is never shown as 0.",
            "未命名项目": "Unnamed project",
            "今日项目": "Today's projects",
            "今天你的 token 走了这些路": "Where your tokens went today",
            "今日路线": "Today's routes",
            "昨日路线": "Yesterday's routes",
            "项目目录名": "Project folder names",
            "还有 %d 个项目": "%d more projects",
            "只显示项目目录名；完整路径仅保存在本机。": "Folder names only; full paths never leave this Mac.",
            "按项目": "By project",
            "更多 Agent 数据源": "More agent sources",
            "先在左侧启用实验 Agent 来源后，可单独勾选以下新数据源。": "Enable experimental agent sources on the left first, then pick individual new sources.",
            "已安装，未启用": "Installed, not enabled",
            "未检测到": "Not detected",
            "检测到已安装的 Agent 会自动纳入统计；主开关关闭时不采集任何实验源。": "Detected agents join the stats automatically; nothing is collected while the master switch is off.",
            "启用实验 Agent 来源": "Enable experimental agent sources",
            "检测到已安装的 Agent 自动计入；可单独关闭某个来源。": "Detected agents are counted automatically; you can turn any source off individually.",
            "数据来源": "Data sources",
            "启用实验数据源": "Enable experimental sources",
            "实验源默认关闭；开启后检测到已安装的 Agent 自动纳入统计，可单独关闭某个来源。只读 usage 字段，不读对话正文。": "Experimental sources are off by default; once enabled, detected agents join the stats automatically and each can be turned off. Usage fields only — never conversation text.",
            "已计入统计": "Counted",
            "零身份读取 · 零网络请求": "Zero identity reads · zero network requests",
            "榜单可见性": "Leaderboard visibility",
            "记录你在 Agent 用量榜的排名。默认隐藏：不读取本地榜单身份、不请求榜单接口。选择「显示」后才会读取本机榜单身份并拉取公开榜单数据。": "Tracks your rank on the Agent usage leaderboard. Hidden by default: no local identity reads and no leaderboard requests. Choosing Show reads the local rank identity and fetches the public leaderboard.",
            "近 30 天": "Last 30 days",
            "每天一个亿": "100M a day",
            "本地统计": "Local Only",
            "不上传代码或对话": "No code or chats uploaded",
            "今日 AI 战绩": "Today’s AI Scorecard",
            "昨日 AI 工作成绩单": "Yesterday’s AI Scorecard",
            "今天我和 AI 一起消耗了": "Today I used with AI",
            "昨天我和 AI 一起完成了": "Yesterday I completed with AI",
            "已完成": "Completed",
            "仅供参考": "Reference only",
            "今日来源": "Today Sources",
            "昨日来源": "Yesterday Sources",
            "今日 Token": "Today Token",
            "按 Token 消耗排序": "Sorted by token usage",
            "完成度": "Completion",
            "总完成度": "Total completion",
            "这是一个新的记录日": "This is a new record day",
            "和前一天基本持平": "About the same as the previous day",
            "比前一天多 %@": "%@ more than previous day",
            "比前一天少 %@": "%@ less than previous day",
            "分享今日卡片": "Share Today Card",
            "分享昨日成绩": "Share Yesterday Recap",
            "分享昨日节奏": "Share Yesterday Rhythm",
            "下载今日卡片": "Download Today Card",
            "下载昨日成绩": "Download Yesterday Recap",
            "下载昨日节奏": "Download Yesterday Rhythm",
            "分享战绩卡片": "Share scorecard",
            "截图与分享": "Capture and Share",
            "还没有昨日数据": "No yesterday data yet",
            "昨日节奏还在等待同步": "Yesterday rhythm is waiting for sync",
            "本地 AI 使用节奏": "Local AI usage rhythm",
            "AI Token 使用追踪": "AI Token Usage Tracking",
            "昨日 AI 节奏": "Yesterday AI Rhythm",
            "完整 24h": "Full 24h",
            "24 小时波形": "24-hour waveform",
            "颜色随时段变化，最高柱是峰值": "Color follows time of day; tallest bar is the peak",
            "峰值": "Peak",
            "峰值 %@": "Peak %@",
            "活跃时段": "Active Hours",
            "%d 个时段": "%d hours",
            "昨日 Token": "Yesterday Tokens",
            "夜间占比": "Night Share",
            "最长连续": "Longest Streak",
            "%d 小时": "%d h",
            "全天总量": "Daily total",
            "昨天的完整 AI 协作节拍": "A full-day AI collaboration rhythm",
            "清晨启动型": "Early Starter",
            "上午规划型": "Morning Planner",
            "下午爆发型": "Afternoon Burst",
            "晚间冲刺型": "Evening Sprint",
            "夜间 Agent 型": "Night Agent",
            "双峰推进型": "Double Peak",
            "碎片推进型": "Fragmented Pusher",
            "一波流型": "One-Shot Sprint",
            "稳定巡航型": "Steady Cruiser",
            "低频轻触型": "Light Touch",
            "一早就把 AI 拉进工作台": "Pulled AI into the workspace early",
            "上午定方向，后面稳稳推进": "Set direction in the morning, then kept moving",
            "午后能量拉满，一段时间集中爆发": "Afternoon energy peaked in a focused burst",
            "晚间突然加速，把任务向前顶了一截": "A sudden evening sprint pushed the work forward",
            "夜里交给 Agent，把任务往前推": "Handed work to agents at night",
            "一天两次拉满，节奏很有层次": "Two strong peaks made the day layered",
            "多时段穿插推进，随手就把活干了": "Moved work forward across scattered moments",
            "集中一波解决主要战斗": "Solved the main battle in one concentrated push",
            "稳定巡航，没有明显掉线": "Cruised steadily without dropping off",
            "轻量使用，保留一点 AI 手感": "Light usage, keeping the AI habit warm",
            "投缘搭子：夜间 Agent 型": "Best rhythm mate: Night Agent",
            "投缘搭子：下午爆发型": "Best rhythm mate: Afternoon Burst",
            "投缘搭子：上午规划型": "Best rhythm mate: Morning Planner",
            "投缘搭子：清晨启动型": "Best rhythm mate: Early Starter",
            "投缘搭子：稳定巡航型": "Best rhythm mate: Steady Cruiser",
            "投缘搭子：一波流型": "Best rhythm mate: One-Shot Sprint",
            "投缘搭子：碎片推进型": "Best rhythm mate: Fragmented Pusher",
            "投缘搭子：双峰推进型": "Best rhythm mate: Double Peak",
            "你负责清晨开局，TA 负责夜里收尾。": "You open early; they close at night.",
            "你负责上午定盘，TA 负责下午冲刺。": "You set the plan; they sprint in the afternoon.",
            "你负责午后爆发，TA 负责上午定盘。": "You burst in the afternoon; they set the morning plan.",
            "你负责深夜推进，TA 负责清晨接棒。": "You push at night; they pick it up in the morning.",
            "你负责两次拉满，TA 负责稳定托底。": "You bring two peaks; they keep the baseline steady.",
            "你负责随手推进，TA 负责集中攻坚。": "You move things in pieces; they handle the focused push.",
            "你负责一波攻坚，TA 负责穿插补位。": "You attack in one wave; they fill in the gaps.",
            "你负责稳定巡航，TA 负责制造峰值。": "You cruise steadily; they create the peaks.",
            "你负责保持手感，TA 负责拉开节奏。": "You keep the habit warm; they set the tempo.",
            "让 TokenStep 按你的节奏记录 Token 消耗": "Let TokenStep track token usage at your rhythm",
            "语言": "Language",
            "选择 TokenStep 的显示语言": "Choose how TokenStep speaks to you",
            "当前语言": "Current language",
            "切换后立即生效": "Changes apply immediately",
            "TokenStep · Local usage tracker": "TokenStep · Local usage tracker",
            "每日目标": "Daily Goal",
            "token / 天": "tokens / day",
            "自动刷新": "Auto Refresh",
            "显示入口": "Display Entry",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "Visible panels check at this rhythm; background refresh slows down based on power state.",
            "手动更新": "Manual refresh",
            "每 %@": "Every %@",
            "当前节奏": "Current rhythm",
            "显示位置": "Display Position",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "On notch displays, show beside the notch. Otherwise use the menu bar.",
            "主题色": "Theme Color",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "The menu bar, rings, activity wall, and buttons follow the theme.",
            "当前主题": "Current theme",
            "登录后自动启动 TokenStep": "Launch TokenStep at login",
            "请先把 TokenStep 拖到 Applications 后再开启开机启动。": "Move TokenStep to Applications before enabling launch at login.",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "Track quietly like steps, so daily token usage is not missed.",
            "自动更新": "Auto Update",
            "自动检查 TokenStep 新版本": "Check for TokenStep updates automatically",
            "有更新时先提醒你，下载前会确认。": "You will be notified first, and asked before downloading.",
            "检查中": "Checking",
            "检查更新": "Check Updates",
            "隐私状态": "Privacy Status",
            "本地隐私保护已开启": "Local privacy protection is on",
            "代码与对话不会离开这台 Mac": "Code and chats never leave this Mac",
            "恢复默认": "Reset Defaults",
            "完成": "Done",
            "可更新": "Update available",
            "正在检查": "Checking",
            "尚未检查": "Not checked yet",
            "当前版本 %@": "Current version %@",
            "发现 %@": "Found %@",
            "下载前询问": "Ask before download",
            "仅安装已签名公证版本": "Only install signed and notarized builds",
            "开机启动": "Launch at Login",
            "已开启": "On",
            "已关闭": "Off",
            "下次登录会自动运行": "Runs automatically next login",
            "需要手动启动 App": "Start the app manually",
            "不读取代码与对话": "Does not read code or chats",
            "不默认上传数据": "Does not upload by default",
            "本机": "This Mac",
            "%d 个客户端": "%d clients",
            "截取设置页": "Capture settings",
            "复制设置截图": "Copy settings screenshot",
            "保存设置 PNG": "Save settings PNG",
            "今日 Token 消耗": "Daily Token Usage",
            "每日 Token 消耗追踪": "Daily Token Tracking",
            "Codex 剩余额度": "Codex Quota",
            "Agent 剩余额度": "Agent Quota",
            "Codex 额度显示": "Show Codex Quota",
            "Agent 额度显示": "Show Agent Quota",
            "Agent 消耗榜": "Agent Usage Rank",
            "Agent 消耗榜显示": "Show Agent Usage Rank",
            "显示": "Show",
            "隐藏": "Hide",
            "自动检测": "Auto Detect",
            "已自动显示": "Shown automatically",
            "已显示": "Shown",
            "已手动隐藏": "Hidden manually",
            "未检测到 Token Rank": "Token Rank not detected",
            "不读取身份与榜单": "No identity or rank access",
            "尚未关联": "Not linked",
            "已自动关联": "Automatically linked",
            "安装 Token Rank 后自动识别": "Detected after Token Rank is installed",
            "数据同步": "Data sync",
            "我的消耗": "My Usage",
            "当前账号": "Current account",
            "关联 Token Rank 账号后显示你的名称、排名和 Token。": "Link a Token Rank account to show your name, rank, and tokens.",
            "加入榜单": "Join leaderboard",
            "管理账号": "Manage account",
            "本机统计": "Local usage",
            "本机账号": "Local account",
            "本机统计 · 今日排名 #%d": "Local usage · Today rank #%d",
            "本机 1 人 + 公开 %d / %d 人（接口上限）": "1 local + %d of %d public users (API limit)",
            "本机榜单共 %d 人": "%d users in local board",
            "我": "Me",
            "显示前 %d 名": "Showing top %d",
            "已显示 %d / %d 人（公开接口上限）": "Showing %d of %d users (public API limit)",
            "共 %d 人": "%d users",
            "设为当前账号": "Set as current account",
            "打开榜单": "Open Rank",
            "全部工具": "All tools",
            "打开榜单页": "Open leaderboard",
            "打开个人页": "Open profile",
            "默认关闭": "Off by default",
            "不会请求榜单": "No rank request",
            "榜单地址不可用": "Leaderboard URL unavailable",
            "暂时无法读取榜单": "Leaderboard unavailable",
            "榜单同步失败，显示上次结果": "Sync failed, showing last result",
            "匿名用户": "Anonymous",
            "今日排名": "Today Rank",
            "今日排名 #%d": "Today rank #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "#%d of %d · Ahead of %d%%",
            "%d 人 · %@": "%d users · %@",
            "今日未上榜": "Not ranked today",
            "榜单暂不可用": "Leaderboard unavailable",
            "点击查看今日榜单": "View today’s leaderboard",
            "点击打开榜单页": "Open leaderboard",
            "今日榜首": "Top today",
            "今日榜单": "Today board",
            "我的今日 Token": "My Today Tokens",
            "全榜今日 Token": "All Today Tokens",
            "主力": "Main",
            "榜单": "Board",
            "上榜：": "Ranked:",
            "实验 Agent 来源": "Experimental Agent Sources",
            "启用 ZCode / Hermes": "Enable ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "Enable ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "Only reads local usage fields, never message content.",
            "已计入实验统计": "Included as experimental",
            "已发现，暂不可统计": "Found, not countable yet",
            "刷新中": "Refreshing",
            "等待刷新": "Waiting for refresh",
            "未发现数据源": "No data source found",
            "暂无可用 usage": "No usable usage yet",
            "结构待适配": "Schema needs support",
            "无法读取": "Unreadable",
            "Agent 工作强度": "Agent Work Intensity",
            "近 7 日均": "7-day avg",
            "打开今日页": "Open Today",
            "Agent Token": "Agent Tokens",
            "5 小时": "5 hours",
            "7 天": "7 days",
            "剩余 %@": "%@ left",
            "等待重置": "Reset pending",
            "即将重置": "Resetting soon",
            "%d 分后重置": "Resets in %d min",
            "约 %d:%02d 后重置": "Resets in about %d:%02d",
            "%d 天后重置": "Resets in %d days",
            "刚刚": "Just now",
            "%d 分钟前": "%d min ago",
            "%d 小时前": "%d hr ago",
            "暂未读取到 Codex 额度": "Codex quota unavailable",
            "暂未读取到 Claude Code 额度": "Claude Code quota unavailable",
            "暂未读取到 Agent 额度": "Agent quota unavailable",
            "打开并登录 Codex 后会自动显示额度。": "Open and sign in to Codex to show quota automatically.",
            "打开并登录 Codex / Claude Code 后会自动显示。": "Open and sign in to Codex / Claude Code to show quota automatically.",
            "打开并登录 Claude Code 后会自动显示。": "Open and sign in to Claude Code to show quota automatically.",
            "复制浮层截图": "Copy popover screenshot",
            "保存浮层 PNG": "Save popover PNG",
            "截取浮层": "Capture popover",
            "细线是每日目标": "Thin line marks the daily goal",
            "手动刷新": "Manual refresh",
            "刷新 %@": "Refresh %@",
            "打开仪表盘": "Open Dashboard",
            "退出": "Quit",
            "青绿": "Green",
            "海蓝": "Ocean",
            "紫藤": "Violet",
            "琥珀": "Amber",
            "石墨": "Graphite",
            "默认": "Default",
            "清爽": "Fresh",
            "温暖": "Warm",
            "专注": "Focus",
            "发现新版本 %@": "New version %@ available",
            "内存占用优化与稳定性改进": "Memory and stability improvements",
            "立即更新": "Update Now",
            "稍后": "Later",
            "TokenStep %@ 可用": "TokenStep %@ Available",
            "安装完成后会自动重启到新版本": "TokenStep will relaunch after installation",
            "更新内容": "What’s New",
            "自动安装到 Applications": "Install to Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "After download, the app in the DMG is verified and replaces the old version",
            "跳过此版本": "Skip Version",
            "安装中": "Installing",
            "安装并重启": "Install & Relaunch",
            "优化 Codex 历史数据读取": "Improved Codex history reading",
            "降低后台刷新 CPU 占用": "Reduced background refresh CPU usage",
            "提升菜单栏同步稳定性": "Improved menu bar sync stability",
            "检查更新失败，请稍后再试。": "Could not check for updates. Please try again later.",
            "新版本没有可下载的 DMG。": "The new version has no downloadable DMG.",
            "下载更新失败，请稍后再试。": "Could not download the update. Please try again later.",
            "新版本未通过签名或公证验证，已停止安装。": "The new version did not pass signing or notarization checks.",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "Automatic install failed. Try again later, or drag TokenStep to Applications manually.",
            "只统计 token 数量": "Only counts token usage",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "Used for daily token usage, trends, and estimated cost.",
            "所有数据文件都保留在这台 Mac 上。": "All data files stay on this Mac.",
            "消耗金额仅供参考": "Cost is only an estimate",
            "按本地价格表粗略估算，不等于真实账单。": "Estimated locally and may not match your real bill.",
            "本地优先": "Local First",
            "本地文件": "Local Files",
            "用量数据": "Usage data",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "If leaderboard support is added later, it will require separate authorization.",
            "截图": "Screenshot",
            "复制截图": "Copy screenshot",
            "保存 PNG": "Save PNG",
            "TokenStep 更新": "TokenStep Update",
            "未检测到可用屏幕": "No available display detected",
            "当前主屏无刘海，已回到菜单栏": "The main display has no notch, so TokenStep is using the menu bar",
            "截图生成失败，请稍后再试。": "Could not create the screenshot. Please try again later.",
            "PNG 文件生成失败，请稍后再试。": "Could not create the PNG file. Please try again later.",
            "JPG 文件生成失败，请稍后再试。": "Could not create the JPG file. Please try again later.",
            "采集脚本退出码 %d": "Collector exited with code %d",
            "采集脚本退出码 %d：%@": "Collector exited with code %d: %@",
            "切换到%@主题": "Switch to %@ theme",
            "TokenStep 自动更新失败": "TokenStep Auto Update Failed",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "Please drag TokenStep from the DMG into Applications manually.",
        ],
        .zhHant: [
            "简体中文": "簡體中文",
            "自动": "自動",
            "刘海左侧": "瀏海左側",
            "刘海右侧": "瀏海右側",
            "菜单栏": "選單列",
            "左侧": "左側",
            "右侧": "右側",
            "跟随系统": "跟隨系統",
            "自动匹配 macOS": "自動匹配 macOS",
            "准备更新": "準備更新",
            "正在下载": "正在下載",
            "正在安装并重启": "正在安裝並重新啟動",
            "更新失败": "更新失敗",
            "菜单栏模式": "選單列模式",
            "自动：刘海旁": "自動：瀏海旁",
            "自动：菜单栏": "自動：選單列",
            "鼠标移入后展开浮层": "滑鼠移入後展開浮層",
            "仅使用右上角菜单栏入口": "僅使用右上角選單列入口",
            "刷新": "重新整理",
            "打开 TokenStep": "開啟 TokenStep",
            "设置": "設定",
            "等待同步": "等待同步",
            "Token 采集超时，请稍后重试": "Token 採集逾時，請稍後重試",
            "Token 重新校准未完成，已保留原统计。": "Token 重新校準未完成，已保留原統計。",
            "TokenStep 已按真实增量重新校准历史 Token。数字可能变小，但历史记录没有丢失。": "TokenStep 已按真實增量重新校準歷史 Token。數字可能變小，但歷史記錄沒有遺失。",
            "关闭": "關閉",
            "手动": "手動",
            "%d 分钟": "%d 分鐘",
            "1 分钟": "1 分鐘",
            "第 %d 圈": "第 %d 圈",
            "第 %d 圈 · %@": "第 %d 圈 · %@",
            "已完成 %d 圈": "已完成 %d 圈",
            "已完成 %@": "已完成 %@",
            "每圈目标 %@": "每圈目標 %@",
            "少": "少",
            "多": "多",
            "活跃": "活躍",
            "达标": "達標",
            "最高": "最高",
            "近 8 个月活动墙": "近 8 個月活動牆",
            "颜色越深，越接近或超过每日目标": "顏色越深，越接近或超過每日目標",
            "颜色越深，用量越高；描边是今天": "顏色越深，用量越高；描邊是今天",
            "%d 个活跃日": "%d 個活躍日",
            "全部明细": "全部明細",
            "%d 条记录，向下滚动查看完整历史": "%d 條記錄，向下捲動查看完整歷史",
            "最近 %d 天，适合保存为截图": "最近 %d 天，適合儲存為截圖",
            "日期": "日期",
            "Token 消耗": "Token 消耗",
            "消耗金额": "消耗金額",
            "主力工具": "主力工具",
            "无": "無",
            "累计 Token 消耗": "累計 Token 消耗",
            "等待下一次同步": "等待下一次同步",
            "最近 30 天": "最近 30 天",
            "颜色越深，圈数越高": "顏色越深，圈數越高",
            "柱越高，用量越多；颜色代表客户端": "柱越高，用量越多；顏色代表客戶端",
            "柱越高，用量越多": "柱越高，用量越多",
            "颜色代表客户端": "顏色代表客戶端",
            "今天 %@": "今天 %@",
            "/ %@ 每圈": "/ %@ 每圈",
            "圈数进度": "圈數進度",
            "按客户端": "按客戶端",
            "按模型": "按模型",
            "今日客户端": "今日客戶端",
            "今日模型": "今日模型",
            "累计总量分布": "累計總量分布",
            "主力模型": "主力模型",
            "本月均值": "本月均值",
            "活跃天数": "活躍天數",
            "达标天数": "達標天數",
            "有 AI 使用的日期": "有 AI 使用的日期",
            "达到每日目标": "達到每日目標",
            "%d圈完成": "%d圈完成",
            "%@进行中": "%@進行中",
            "所有本机记录": "所有本機記錄",
            "今日": "今日",
            "历史": "歷史",
            "统计": "統計",
            "模型与工具": "模型與工具",
            "隐私": "隱私",
            "今日消耗": "今日消耗",
            "历史活动": "歷史活動",
            "用量统计": "用量統計",
            "今天的 Token 使用节奏": "今天的 Token 使用節奏",
            "长期节奏和所有历史记录": "長期節奏和所有歷史記錄",
            "按客户端和模型拆开看": "按客戶端和模型拆開看",
            "只统计数量，不读取内容": "只統計數量，不讀取內容",
            "保存当前页 PNG（最近 30 天）": "儲存目前頁 PNG（最近 30 天）",
            "保存当前页 PNG": "儲存目前頁 PNG",
            "复制当前页截图": "複製目前頁截圖",
            "截取当前页": "擷取目前頁",
            "更新": "更新",
            "同步中": "同步中",
            "已同步": "已同步",
            "暂无数据": "暫無資料",
            "数据待更新": "資料待更新",
            "同步失败": "同步失敗",
            "部分来源失败": "部分來源失敗",
            "显示最后成功数据": "顯示最後成功資料",
            "最后成功 %@": "最後成功 %@",
            "%d 天前": "%d 天前",
            "消耗金额（估算）": "消耗金額（估算）",
            "按 API 列表价估算，不代表订阅或实际账单。": "按 API 列表價估算，不代表訂閱或實際帳單。",
            "失败来源：%@": "失敗來源：%@",
            "数据状态说明": "資料狀態說明",
            "数据在正常刷新周期内成功获取。": "資料在正常刷新週期內成功取得。",
            "超过正常刷新周期，最近一次尝试没有失败。": "超過正常刷新週期，最近一次嘗試沒有失敗。",
            "最近一次尝试失败，当前展示最后成功数据。": "最近一次嘗試失敗，目前顯示最後成功資料。",
            "同一轮刷新中部分数据来源失败，其余正常。": "同一輪刷新中部分資料來源失敗，其餘正常。",
            "该数据从未成功获取，不会显示为 0。": "該資料從未成功取得，不會顯示為 0。",
            "未命名项目": "未命名項目",
            "今日项目": "今日項目",
            "今天你的 token 走了这些路": "今天你的 token 走了這些路",
            "今日路线": "今日路線",
            "昨日路线": "昨日路線",
            "项目目录名": "專案資料夾名稱",
            "还有 %d 个项目": "還有 %d 個項目",
            "只显示项目目录名；完整路径仅保存在本机。": "只顯示專案資料夾名稱；完整路徑僅保存在本機。",
            "按项目": "按專案",
            "更多 Agent 数据源": "更多 Agent 資料來源",
            "先在左侧启用实验 Agent 来源后，可单独勾选以下新数据源。": "先在左側啟用實驗 Agent 來源後，可單獨勾選以下新資料來源。",
            "已安装，未启用": "已安裝，未啟用",
            "未检测到": "未偵測到",
            "检测到已安装的 Agent 会自动纳入统计；主开关关闭时不采集任何实验源。": "偵測到已安裝的 Agent 會自動納入統計；主開關關閉時不採集任何實驗來源。",
            "启用实验 Agent 来源": "啟用實驗 Agent 來源",
            "检测到已安装的 Agent 自动计入；可单独关闭某个来源。": "偵測到已安裝的 Agent 自動計入；可單獨關閉某個來源。",
            "数据来源": "資料來源",
            "启用实验数据源": "啟用實驗資料來源",
            "实验源默认关闭；开启后检测到已安装的 Agent 自动纳入统计，可单独关闭某个来源。只读 usage 字段，不读对话正文。": "實驗來源預設關閉；開啟後偵測到已安裝的 Agent 會自動納入統計，可單獨關閉某個來源。只讀 usage 欄位，不讀對話正文。",
            "已计入统计": "已計入統計",
            "零身份读取 · 零网络请求": "零身份讀取 · 零網路請求",
            "榜单可见性": "榜單可見性",
            "记录你在 Agent 用量榜的排名。默认隐藏：不读取本地榜单身份、不请求榜单接口。选择「显示」后才会读取本机榜单身份并拉取公开榜单数据。": "記錄你在 Agent 用量榜的排名。預設隱藏：不讀取本機榜單身份、不請求榜單介面。選擇「顯示」後才會讀取本機榜單身份並拉取公開榜單資料。",
            "近 30 天": "近 30 天",
            "每天一个亿": "每天一個億",
            "本地统计": "本地統計",
            "不上传代码或对话": "不上傳程式碼或對話",
            "今日 AI 战绩": "今日 AI 戰績",
            "昨日 AI 工作成绩单": "昨日 AI 工作成績單",
            "今天我和 AI 一起消耗了": "今天我和 AI 一起消耗了",
            "昨天我和 AI 一起完成了": "昨天我和 AI 一起完成了",
            "已完成": "已完成",
            "仅供参考": "僅供參考",
            "今日来源": "今日來源",
            "昨日来源": "昨日來源",
            "今日 Token": "今日 Token",
            "按 Token 消耗排序": "按 Token 消耗排序",
            "完成度": "完成度",
            "总完成度": "總完成度",
            "这是一个新的记录日": "這是一個新的記錄日",
            "和前一天基本持平": "和前一天基本持平",
            "比前一天多 %@": "比前一天多 %@",
            "比前一天少 %@": "比前一天少 %@",
            "分享今日卡片": "分享今日卡片",
            "分享昨日成绩": "分享昨日成績",
            "分享昨日节奏": "分享昨日節奏",
            "下载今日卡片": "下載今日卡片",
            "下载昨日成绩": "下載昨日成績",
            "下载昨日节奏": "下載昨日節奏",
            "分享战绩卡片": "分享戰績卡片",
            "截图与分享": "截圖與分享",
            "还没有昨日数据": "還沒有昨日資料",
            "昨日节奏还在等待同步": "昨日節奏還在等待同步",
            "本地 AI 使用节奏": "本地 AI 使用節奏",
            "AI Token 使用追踪": "AI Token 使用追蹤",
            "昨日 AI 节奏": "昨日 AI 節奏",
            "完整 24h": "完整 24h",
            "24 小时波形": "24 小時波形",
            "颜色随时段变化，最高柱是峰值": "顏色隨時段變化，最高柱是峰值",
            "峰值": "峰值",
            "峰值 %@": "峰值 %@",
            "活跃时段": "活躍時段",
            "%d 个时段": "%d 個時段",
            "昨日 Token": "昨日 Token",
            "夜间占比": "夜間占比",
            "最长连续": "最長連續",
            "%d 小时": "%d 小時",
            "全天总量": "全天總量",
            "昨天的完整 AI 协作节拍": "昨天的完整 AI 協作節拍",
            "清晨启动型": "清晨啟動型",
            "上午规划型": "上午規劃型",
            "下午爆发型": "下午爆發型",
            "晚间冲刺型": "晚間衝刺型",
            "夜间 Agent 型": "夜間 Agent 型",
            "双峰推进型": "雙峰推進型",
            "碎片推进型": "碎片推進型",
            "一波流型": "一波流型",
            "稳定巡航型": "穩定巡航型",
            "低频轻触型": "低頻輕觸型",
            "一早就把 AI 拉进工作台": "一早就把 AI 拉進工作台",
            "上午定方向，后面稳稳推进": "上午定方向，後面穩穩推進",
            "午后能量拉满，一段时间集中爆发": "午後能量拉滿，一段時間集中爆發",
            "晚间突然加速，把任务向前顶了一截": "晚間突然加速，把任務向前頂了一截",
            "夜里交给 Agent，把任务往前推": "夜裡交給 Agent，把任務往前推",
            "一天两次拉满，节奏很有层次": "一天兩次拉滿，節奏很有層次",
            "多时段穿插推进，随手就把活干了": "多時段穿插推進，隨手就把活幹了",
            "集中一波解决主要战斗": "集中一波解決主要戰鬥",
            "稳定巡航，没有明显掉线": "穩定巡航，沒有明顯掉線",
            "轻量使用，保留一点 AI 手感": "輕量使用，保留一點 AI 手感",
            "投缘搭子：夜间 Agent 型": "投緣搭子：夜間 Agent 型",
            "投缘搭子：下午爆发型": "投緣搭子：下午爆發型",
            "投缘搭子：上午规划型": "投緣搭子：上午規劃型",
            "投缘搭子：清晨启动型": "投緣搭子：清晨啟動型",
            "投缘搭子：稳定巡航型": "投緣搭子：穩定巡航型",
            "投缘搭子：一波流型": "投緣搭子：一波流型",
            "投缘搭子：碎片推进型": "投緣搭子：碎片推進型",
            "投缘搭子：双峰推进型": "投緣搭子：雙峰推進型",
            "你负责清晨开局，TA 负责夜里收尾。": "你負責清晨開局，TA 負責夜裡收尾。",
            "你负责上午定盘，TA 负责下午冲刺。": "你負責上午定盤，TA 負責下午衝刺。",
            "你负责午后爆发，TA 负责上午定盘。": "你負責午後爆發，TA 負責上午定盤。",
            "你负责深夜推进，TA 负责清晨接棒。": "你負責深夜推進，TA 負責清晨接棒。",
            "你负责两次拉满，TA 负责稳定托底。": "你負責兩次拉滿，TA 負責穩定托底。",
            "你负责随手推进，TA 负责集中攻坚。": "你負責隨手推進，TA 負責集中攻堅。",
            "你负责一波攻坚，TA 负责穿插补位。": "你負責一波攻堅，TA 負責穿插補位。",
            "你负责稳定巡航，TA 负责制造峰值。": "你負責穩定巡航，TA 負責製造峰值。",
            "你负责保持手感，TA 负责拉开节奏。": "你負責保持手感，TA 負責拉開節奏。",
            "让 TokenStep 按你的节奏记录 Token 消耗": "讓 TokenStep 按你的節奏記錄 Token 消耗",
            "语言": "語言",
            "选择 TokenStep 的显示语言": "選擇 TokenStep 的顯示語言",
            "当前语言": "目前語言",
            "切换后立即生效": "切換後立即生效",
            "TokenStep · Local usage tracker": "TokenStep · 本地用量追蹤器",
            "每日目标": "每日目標",
            "token / 天": "token / 天",
            "自动刷新": "自動重新整理",
            "显示入口": "顯示入口",
            "面板可见时按此频率检查；后台会根据供电状态降低频率。": "面板可見時按此頻率檢查；背景會依供電狀態降低頻率。",
            "手动更新": "手動更新",
            "每 %@": "每 %@",
            "当前节奏": "目前節奏",
            "显示位置": "顯示位置",
            "刘海屏显示在刘海旁，其他屏幕使用菜单栏。": "瀏海螢幕顯示在瀏海旁，其他螢幕使用選單列。",
            "主题色": "主題色",
            "菜单栏、圆环、活动墙和按钮会一起跟随主题变化。": "選單列、圓環、活動牆和按鈕會一起跟隨主題變化。",
            "当前主题": "目前主題",
            "登录后自动启动 TokenStep": "登入後自動啟動 TokenStep",
            "请先把 TokenStep 拖到 Applications 后再开启开机启动。": "請先把 TokenStep 拖到 Applications 後再開啟開機啟動。",
            "像步数一样默默记录，避免漏掉每天的 Token 消耗。": "像步數一樣默默記錄，避免漏掉每天的 Token 消耗。",
            "自动更新": "自動更新",
            "自动检查 TokenStep 新版本": "自動檢查 TokenStep 新版本",
            "有更新时先提醒你，下载前会确认。": "有更新時先提醒你，下載前會確認。",
            "检查中": "檢查中",
            "检查更新": "檢查更新",
            "隐私状态": "隱私狀態",
            "本地隐私保护已开启": "本地隱私保護已開啟",
            "代码与对话不会离开这台 Mac": "程式碼與對話不會離開這台 Mac",
            "恢复默认": "恢復預設",
            "完成": "完成",
            "可更新": "可更新",
            "正在检查": "正在檢查",
            "尚未检查": "尚未檢查",
            "当前版本 %@": "目前版本 %@",
            "发现 %@": "發現 %@",
            "下载前询问": "下載前詢問",
            "仅安装已签名公证版本": "僅安裝已簽名公證版本",
            "开机启动": "開機啟動",
            "已开启": "已開啟",
            "已关闭": "已關閉",
            "下次登录会自动运行": "下次登入會自動執行",
            "需要手动启动 App": "需要手動啟動 App",
            "不读取代码与对话": "不讀取程式碼與對話",
            "不默认上传数据": "不預設上傳資料",
            "本机": "本機",
            "%d 个客户端": "%d 個客戶端",
            "截取设置页": "擷取設定頁",
            "复制设置截图": "複製設定截圖",
            "保存设置 PNG": "儲存設定 PNG",
            "今日 Token 消耗": "今日 Token 消耗",
            "每日 Token 消耗追踪": "每日 Token 消耗追蹤",
            "Codex 剩余额度": "Codex 剩餘額度",
            "Agent 剩余额度": "Agent 剩餘額度",
            "Codex 额度显示": "顯示 Codex 額度",
            "Agent 额度显示": "顯示 Agent 額度",
            "Agent 消耗榜": "Agent 消耗榜",
            "Agent 消耗榜显示": "顯示 Agent 消耗榜",
            "显示": "顯示",
            "隐藏": "隱藏",
            "自动检测": "自動偵測",
            "已自动显示": "已自動顯示",
            "已显示": "已顯示",
            "已手动隐藏": "已手動隱藏",
            "未检测到 Token Rank": "未偵測到 Token Rank",
            "不读取身份与榜单": "不讀取身分與榜單",
            "尚未关联": "尚未關聯",
            "已自动关联": "已自動關聯",
            "安装 Token Rank 后自动识别": "安裝 Token Rank 後自動識別",
            "数据同步": "資料同步",
            "我的消耗": "我的消耗",
            "当前账号": "目前帳號",
            "关联 Token Rank 账号后显示你的名称、排名和 Token。": "關聯 Token Rank 帳號後顯示你的名稱、排名和 Token。",
            "加入榜单": "加入榜單",
            "管理账号": "管理帳號",
            "本机统计": "本機統計",
            "本机账号": "本機帳號",
            "本机统计 · 今日排名 #%d": "本機統計 · 今日排名 #%d",
            "本机 1 人 + 公开 %d / %d 人（接口上限）": "本機 1 人 + 公開 %d / %d 人（介面上限）",
            "本机榜单共 %d 人": "本機榜單共 %d 人",
            "我": "我",
            "显示前 %d 名": "顯示前 %d 名",
            "已显示 %d / %d 人（公开接口上限）": "已顯示 %d / %d 人（公開介面上限）",
            "共 %d 人": "共 %d 人",
            "设为当前账号": "設為目前帳號",
            "打开榜单": "開啟榜單",
            "全部工具": "全部工具",
            "打开榜单页": "開啟榜單頁",
            "打开个人页": "開啟個人頁",
            "默认关闭": "預設關閉",
            "不会请求榜单": "不會請求榜單",
            "榜单地址不可用": "榜單地址不可用",
            "暂时无法读取榜单": "暫時無法讀取榜單",
            "榜单同步失败，显示上次结果": "榜單同步失敗，顯示上次結果",
            "匿名用户": "匿名使用者",
            "今日排名": "今日排名",
            "今日排名 #%d": "今日排名 #%d",
            "第 %d / %d · 超过 %d%% 参榜用户": "第 %d / %d · 超過 %d%% 參榜使用者",
            "%d 人 · %@": "%d 人 · %@",
            "今日未上榜": "今日未上榜",
            "榜单暂不可用": "榜單暫不可用",
            "点击查看今日榜单": "點擊查看今日榜單",
            "点击打开榜单页": "點擊開啟榜單頁",
            "今日榜首": "今日榜首",
            "今日榜单": "今日榜單",
            "我的今日 Token": "我的今日 Token",
            "全榜今日 Token": "全榜今日 Token",
            "主力": "主力",
            "榜单": "榜單",
            "上榜：": "上榜：",
            "实验 Agent 来源": "實驗 Agent 來源",
            "启用 ZCode / Hermes": "啟用 ZCode / Hermes",
            "启用 ZCode / Hermes / WorkBuddy": "啟用 ZCode / Hermes / WorkBuddy",
            "只读取本地 usage 字段，不读取对话正文。": "只讀取本地 usage 欄位，不讀取對話正文。",
            "已计入实验统计": "已計入實驗統計",
            "已发现，暂不可统计": "已發現，暫不可統計",
            "刷新中": "刷新中",
            "等待刷新": "等待刷新",
            "未发现数据源": "未發現資料來源",
            "暂无可用 usage": "暫無可用 usage",
            "结构待适配": "結構待適配",
            "无法读取": "無法讀取",
            "Agent 工作强度": "Agent 工作強度",
            "近 7 日均": "近 7 日均",
            "打开今日页": "開啟今日頁",
            "Agent Token": "Agent Token",
            "5 小时": "5 小時",
            "7 天": "7 天",
            "剩余 %@": "剩餘 %@",
            "等待重置": "等待重置",
            "即将重置": "即將重置",
            "%d 分后重置": "%d 分後重置",
            "约 %d:%02d 后重置": "約 %d:%02d 後重置",
            "%d 天后重置": "%d 天後重置",
            "刚刚": "剛剛",
            "%d 分钟前": "%d 分鐘前",
            "%d 小时前": "%d 小時前",
            "暂未读取到 Codex 额度": "暫未讀取到 Codex 額度",
            "暂未读取到 Claude Code 额度": "暫未讀取到 Claude Code 額度",
            "暂未读取到 Agent 额度": "暫未讀取到 Agent 額度",
            "打开并登录 Codex 后会自动显示额度。": "開啟並登入 Codex 後會自動顯示額度。",
            "打开并登录 Codex / Claude Code 后会自动显示。": "開啟並登入 Codex / Claude Code 後會自動顯示。",
            "打开并登录 Claude Code 后会自动显示。": "開啟並登入 Claude Code 後會自動顯示。",
            "复制浮层截图": "複製浮層截圖",
            "保存浮层 PNG": "儲存浮層 PNG",
            "截取浮层": "擷取浮層",
            "细线是每日目标": "細線是每日目標",
            "手动刷新": "手動重新整理",
            "刷新 %@": "重新整理 %@",
            "打开仪表盘": "開啟儀表板",
            "退出": "退出",
            "青绿": "青綠",
            "海蓝": "海藍",
            "紫藤": "紫藤",
            "琥珀": "琥珀",
            "石墨": "石墨",
            "默认": "預設",
            "清爽": "清爽",
            "温暖": "溫暖",
            "专注": "專注",
            "发现新版本 %@": "發現新版本 %@",
            "内存占用优化与稳定性改进": "記憶體佔用最佳化與穩定性改進",
            "立即更新": "立即更新",
            "稍后": "稍後",
            "TokenStep %@ 可用": "TokenStep %@ 可用",
            "安装完成后会自动重启到新版本": "安裝完成後會自動重新啟動到新版本",
            "更新内容": "更新內容",
            "自动安装到 Applications": "自動安裝到 Applications",
            "下载后会验证 DMG 中的 App，并替换旧版本": "下載後會驗證 DMG 中的 App，並替換舊版本",
            "跳过此版本": "略過此版本",
            "安装中": "安裝中",
            "安装并重启": "安裝並重新啟動",
            "优化 Codex 历史数据读取": "最佳化 Codex 歷史資料讀取",
            "降低后台刷新 CPU 占用": "降低背景重新整理 CPU 佔用",
            "提升菜单栏同步稳定性": "提升選單列同步穩定性",
            "检查更新失败，请稍后再试。": "檢查更新失敗，請稍後再試。",
            "新版本没有可下载的 DMG。": "新版本沒有可下載的 DMG。",
            "下载更新失败，请稍后再试。": "下載更新失敗，請稍後再試。",
            "新版本未通过签名或公证验证，已停止安装。": "新版本未通過簽名或公證驗證，已停止安裝。",
            "自动安装失败，请稍后重试，或手动把 TokenStep 拖到 Applications。": "自動安裝失敗，請稍後重試，或手動把 TokenStep 拖到 Applications。",
            "只统计 token 数量": "只統計 token 數量",
            "用于计算今日 Token 消耗、历史趋势和消耗金额。": "用於計算今日 Token 消耗、歷史趨勢和消耗金額。",
            "所有数据文件都保留在这台 Mac 上。": "所有資料檔案都保留在這台 Mac 上。",
            "消耗金额仅供参考": "消耗金額僅供參考",
            "按本地价格表粗略估算，不等于真实账单。": "按本地價格表粗略估算，不等於真實帳單。",
            "本地优先": "本地優先",
            "本地文件": "本地檔案",
            "用量数据": "用量資料",
            "后续如果接入排行榜，会单独做授权和确认，不会默认上传。": "後續如果接入排行榜，會單獨做授權和確認，不會預設上傳。",
            "截图": "截圖",
            "复制截图": "複製截圖",
            "保存 PNG": "儲存 PNG",
            "TokenStep 更新": "TokenStep 更新",
            "未检测到可用屏幕": "未偵測到可用螢幕",
            "当前主屏无刘海，已回到菜单栏": "目前主螢幕無瀏海，已回到選單列",
            "截图生成失败，请稍后再试。": "截圖產生失敗，請稍後再試。",
            "PNG 文件生成失败，请稍后再试。": "PNG 檔案產生失敗，請稍後再試。",
            "JPG 文件生成失败，请稍后再试。": "JPG 檔案產生失敗，請稍後再試。",
            "采集脚本退出码 %d": "採集腳本退出碼 %d",
            "采集脚本退出码 %d：%@": "採集腳本退出碼 %d：%@",
            "切换到%@主题": "切換到%@主題",
            "TokenStep 自动更新失败": "TokenStep 自動更新失敗",
            "请手动把 DMG 里的 TokenStep 拖到 Applications。": "請手動把 DMG 裡的 TokenStep 拖到 Applications。"
        ]
    ]
}

func L(_ key: String) -> String {
    TokenStepLocalization.text(key)
}

func LFormat(_ key: String, _ arguments: CVarArg...) -> String {
    TokenStepLocalization.format(key, arguments)
}
